### ISSUE TITLE
Add license(s)

### ISSUE THREAD

**Issue by stvnwn** [zaxutic/kh2fm-rando-tracker#10]
For future (and potentially past) iterations to the software and assets, if you choose to do so.

[This website](https://choosealicense.com/) provides "non-judgmental guidance on choosing a license for your open source project".

**Comment by zaxutic** [comment]
Originally I didn't put a license on the software as it was technically derived from Kokemon's original code (even if almost all of the code was completely different) and I wasn't sure about the licensing rules around that, however I believe the [Vue rewrite](https://github.com/zaxutic/kh2fm-rando-tracker/tree/next) constitutes as my own work that I can license

**Comment by stvnwn** [comment]
That's fair.

Is there any chance that the images can be licensed separately, perhaps under a Creative Commons license?

**Comment by zaxutic** [comment]
I'm not completely sure about image rights, as some are derived from assets belonging to Square Enix, though others probably would. Perhaps @Televo might be able to shed some light on this (the designer of most of the assets used in the tracker, and hence would also be the person to license these images)

**Comment by Televo** [comment]
Hey guys, I won't be able to give much insight here since I've never dealt with licenses directly before, however after reading through the website above I agree that one of the CC-BY-4.0 licenses does seem like the way to go.
